// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXNA96uxNi1AjK9BqV_3lGiU1cSkT97q8',
    appId: '1:942438440222:web:4b64678c936f6a3fcabd0f',
    messagingSenderId: '942438440222',
    projectId: 'dalel-54943',
    authDomain: 'dalel-54943.firebaseapp.com',
    storageBucket: 'dalel-54943.appspot.com',
    measurementId: 'G-6R6Q7ELQ2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1tJ0DEZ_OaX4ZrFc4b6no1VTFyjqgiI',
    appId: '1:942438440222:android:8a226b74927a474fcabd0f',
    messagingSenderId: '942438440222',
    projectId: 'dalel-54943',
    storageBucket: 'dalel-54943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmURI_SUoYIjAzJ9yZzP6LthQA3Dz5xog',
    appId: '1:942438440222:ios:d9fe55c535021ab8cabd0f',
    messagingSenderId: '942438440222',
    projectId: 'dalel-54943',
    storageBucket: 'dalel-54943.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmURI_SUoYIjAzJ9yZzP6LthQA3Dz5xog',
    appId: '1:942438440222:ios:d9fe55c535021ab8cabd0f',
    messagingSenderId: '942438440222',
    projectId: 'dalel-54943',
    storageBucket: 'dalel-54943.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXNA96uxNi1AjK9BqV_3lGiU1cSkT97q8',
    appId: '1:942438440222:web:9ca5bde70a408860cabd0f',
    messagingSenderId: '942438440222',
    projectId: 'dalel-54943',
    authDomain: 'dalel-54943.firebaseapp.com',
    storageBucket: 'dalel-54943.appspot.com',
    measurementId: 'G-EWKZENFL74',
  );
}
